name: application_base
description: "Unified base for Flutter applications"
version: 0.1.7
homepage: https://github.com/AlexSeednov/application_base

environment:
  # Flutter SDK supported versions
  # Pinned packages
  # https://github.com/flutter/flutter/blob/3.38.7/packages/flutter/pubspec.yaml
  # https://github.com/flutter/flutter/blob/stable/CHANGELOG.md
  flutter: '>=3.38.7'  

  # Dart SDK supported versions
  # https://docs.flutter.dev/release/archive
  # https://dart.googlesource.com/sdk/+/stable/CHANGELOG.md
  sdk: '>=3.10.7'

# Last update - 23.01.2026
dependencies:
  # All platform supported
  auto_route: 11.1.0

  # All platform supported
  connectivity_plus: ^7.0.0

  # All platform supported
  cross_file: ^0.3.5+1

  # Base SDK
  flutter:
    sdk: flutter

  # All platform supported
  flutter_secure_storage: ^10.0.0

  # All platform supported
  get_it: ^9.2.0

  # All platform supported
  hive_ce: ^2.19.1

  # All platform supported
  hive_ce_flutter: ^2.3.4

  # All platform supported
  http: ^1.6.0
  
  # All platform supported
  logger: ^2.6.2

  # All platform supported
  # Pinned by Flutter
  # meta: ^1.18.0
  meta: ^1.17.0

  # All platform supported
  rxdart: ^0.28.0
  
  # All platform supported
  share_plus: ^12.0.1

  # All platform supported
  url_launcher: ^6.3.2

#
dev_dependencies:
  #
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
